#!/bin/sh
#
# Install hpctraceviewer into hpctoolkit directory.
#
# Usage: ./install dir
#
# where "dir" is the top-level hpctoolkit install directory, the same
# directory specified as --prefix in hpctoolkit's configure.  Run this
# script in its own directory, as ./install.
#
# $Id: install 327 2009-04-22 19:15:51Z krentel $
#

die()
{
    echo "$0: $*" 1>&2
    exit 1
}

usage()
{
    cat <<EOF
Usage: $0 hpctoolkit-prefix-directory
EOF
    exit 0
}

#
# See if the directory ($1) looks like an hpctoolkit install
# directory.
#
hpctk_dir="$1"
test "x$hpctk_dir" != x || usage

if test -x "${hpctk_dir}/bin/hpcrun" -o -x "${hpctk_dir}/bin/hpclink" \
    && test -d "${hpctk_dir}/libexec/hpctoolkit"
then :
else
    cat <<EOF

Warning: possible bad directory: $hpctk_dir

This directory does not look like an hpctoolkit install directory.
Either the directory does not exist, or hpctoolkit is not installed
there.  This is not necessarily fatal, but it is suspicious and you
should double check the directory.

EOF
    echo -n "Continue with the install? [ny] "
    read ans
    case "$ans" in
	[yY]* ) ;;
	* ) exit 1 ;;
    esac
fi

#
# Install hpctraceviewer.sh into bin (as hpctraceviewer), other files into
# libexec, and reset permissions.
#
bin_dir="${hpctk_dir}/bin"
libexec_dir="${hpctk_dir}/libexec/hpctraceviewer"

mkdir -p "$bin_dir" "$libexec_dir" \
    || die "unable to mkdir install directories"

cp -f hpctraceviewer.sh "${bin_dir}/hpctraceviewer" \
    || die "unable to install bin/hpctraceviewer"

cp -f hpctraceviewer hpctraceviewer.ini "$libexec_dir" \
    || die "unable to install libexec files"

tar cf - configuration plugins | ( cd "$libexec_dir" && tar xvf - )
test $? -eq 0 || die "unable to install libexec files"

echo "Resetting permissions ..."
chmod 755 "${bin_dir}/hpctraceviewer" "${libexec_dir}/hpctraceviewer"

# NOTE: the find idiom below is used to deftly handle file names with embedded spaces 
find "$libexec_dir" -type d -exec chmod 755 {} \;
find "$libexec_dir" -type f -exec chmod a+r {} \;

echo "hpctraceviewer install done"
exit 0
