#!/bin/sh
#
# Copyright (c) 2002-2012, Rice University.
# See the file README.License for details.
#
# Install hpcviewer into hpctoolkit directory.
# This script is only for Unix and X windows.
#
# Usage: ./install [-j java-dir] install-dir
#
# where 'java-dir' is a Java jdk or jre directory,
# and 'install-dir' is the directory in which to install.
#
# Run this script from its own directory as ./install.
#
# $Id$
#

name=hpctraceviewer
install_subdirs='configuration plugins'

#------------------------------------------------------------
# Error messages
#------------------------------------------------------------

die()
{
    echo "$0: $*" 1>&2
    exit 1
}

usage()
{
    cat <<EOF
Usage: ./install [-j java-dir] install-dir

where 'java-dir' is a Java jdk or jre directory,
and 'install-dir' is the directory in which to install.

Run this script from its own directory as ./install.
EOF
    exit 0
}

#------------------------------------------------------------
# Command-Line Options
#------------------------------------------------------------

java_dir=
install_dir=

while test -n "$1"
do
    arg="$1" ; shift
    case "$arg" in
	-h | -help | --help )
	    usage
	    ;;
	-j | -java | --java )
	    test "x$1" != x || die "missing directory for $arg"
	    java_dir="$1"
	    shift
	    ;;
	-* )
	    die "unknown option: $arg"
	    ;;
	* )
	    install_dir="$arg"
	    break
	    ;;
    esac
done

test "x$install_dir" != x || usage

#------------------------------------------------------------
# Java tests
#------------------------------------------------------------

# Java_dir is the jdk or jre directory, if specified.

java_bindir=
if test -n "$java_dir" ; then
    if test -f "${java_dir}/bin/java" ; then
	java_bindir="${java_dir}/bin"
    elif test -f "${java_dir}/java" ; then
	java_bindir="${java_dir}"
    else
	die "unable to find java in: $java_dir"
    fi
    PATH="${java_bindir}:$PATH"
fi

# Check that version is 1.5 or later.

java_version=`java -version 2>&1 | grep -i java | grep -i vers | head -1`
if test "x$java_version" = x ; then
    die "unable to find program 'java' on your PATH"
fi
minor=`expr "$java_version" : '[^.]*\.\([0-9]*\)'`
test "$minor" -ge 5 >/dev/null 2>&1
if test $? -ne 0 ; then
    die "$java_version is too old, use Java 1.5 or later"
fi

#------------------------------------------------------------
# Install the viewer and reset permissions.
#------------------------------------------------------------

bin_dir="${install_dir}/bin"
libexec_dir="${install_dir}/libexec/$name"
binary_file="$name"
ini_file="${name}.ini"
sh_file="${name}.sh"

mkdir -p "$bin_dir" "$libexec_dir" \
    || die "unable to mkdir install directories"

cp -f "$sh_file" "${bin_dir}/$name" \
    || die "unable to install bin files"

cp -f "$binary_file" "$ini_file" "$libexec_dir" \
    || die "unable to install libexec files"

if test -n "$java_bindir" ; then
    orig="${bin_dir}/${name}"
    tmp="${bin_dir}/${name}.tmp"
    rm -f "$tmp"
    mv -f "$orig" "$tmp"
    sed -e "s,^#.*JAVA_BINDIR=.*\$,JAVA_BINDIR='${java_bindir}'," \
	<"$tmp"  >"$orig"
    rm -f "$tmp"
fi

tar cf - $install_subdirs | ( cd "$libexec_dir" && tar xvf - )
test $? -eq 0 || die "unable to install libexec files"

# Note: the find idiom below is used to handle file names with
# embedded spaces.

echo "Resetting permissions ..."
chmod a+rx "${bin_dir}/$name" "${libexec_dir}/$binary_file"
find "$libexec_dir" -type d -exec chmod a+rx {} \;
find "$libexec_dir" -type f -exec chmod a+r  {} \;

echo "done"
exit 0
