#!/bin/sh
#
# Install hpcviewer into hpctoolkit directory.
#
# Usage: ./install dir
#
# where "dir" is the top-level hpctoolkit install directory, the same
# directory specified as --prefix in hpctoolkit's configure.  Run this
# script in its own directory, as ./install.
#
# $Id$
#

die()
{
    echo "$0: $*" 1>&2
    exit 1
}

usage()
{
    cat <<EOF
Usage: $0 hpctoolkit-prefix-directory
EOF
    exit 0
}

#
# See if the directory ($1) looks like an hpctoolkit install
# directory.
#
hpctk_dir="$1"
test "x$hpctk_dir" != x || usage

if test ! -x "${hpctk_dir}/bin/hpcrun" \
    || test ! -d "${hpctk_dir}/libexec/hpctoolkit"
then
    cat <<EOF

Warning: possible bad directory: $hpctk_dir

This directory does not look like an hpctoolkit install directory.
Either the directory does not exist, or hpctoolkit is not installed
there.  This is not necessarily fatal, but it is suspicious and you
should double check the directory.

EOF
    echo -n "Continue with the install? [ny] "
    read ans
    case "$ans" in
	[yY]* ) ;;
	* ) exit 1 ;;
    esac
fi

#
# Install hpcviewer.sh into bin (as hpcviewer), other files into
# libexec, and reset permissions.
#
bin_dir="${hpctk_dir}/bin"
libexec_dir="${hpctk_dir}/libexec/hpcviewer"

mkdir -p "$bin_dir" "$libexec_dir" \
    || die "unable to mkdir install directories"

cp -f hpcviewer.sh "${bin_dir}/hpcviewer" \
    || die "unable to install bin/hpcviewer"

cp -f hpcviewer hpcviewer.ini "$libexec_dir" \
    || die "unable to install libexec files"

tar cf - configuration plugins | ( cd "$libexec_dir" && tar xvf - )
test $? -eq 0 || die "unable to install libexec files"

echo "Resetting permissions ..."
chmod 755 "${bin_dir}/hpcviewer" "${libexec_dir}/hpcviewer"
find "$libexec_dir" -type d -print | xargs chmod 755
find "$libexec_dir" -type f -print | xargs chmod a+r

echo "hpcviewer install done"
exit 0
