#!/bin/bash
# get the install directory
bdir=`dirname $0`
# set the workspace directory into home directory
workspacedir=${HOME}/.hpctoolkit/hpcviewer
# output message to user
echo "Running ${bdir}/hpcviewer -data ${workspacedir} $@"
# run the actual hpcviewer
${bdir}/../libexec/hpcviewer/hpcviewer -data ${workspacedir} $@
